### ISSUE TITLE
Default proxy filename

### ISSUE THREAD

**Issue by matz-e** [vkuznet/dasgoclient#1]
Hi,

It would be great if we didn't have to export the proxy filename via `X509_USER_PROXY`. I think by default the file is named `/tmp/x509up_u$UID`, and I think it would be nice if the environment variable would have to be only set when that file is not found.

Thanks,
Matthias

**Comment by vkuznet** [comment]
Mattias,
it is fixed now (commit 3442fca..e8e1f2f). Feel free to test it, just use
/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_linux
again, it is updated.
Best,
Valentin.

**Comment by matz-e** [comment]
Great, that was fast, thank you! I will keep testing it.

Thanks,
Matthias
